### ISSUE TITLE
text and background also white

### ISSUE THREAD

**Issue by airzhe** [elizabethsiegle/gemini-multimodal-chat#1]
<img width="923" alt="截屏2023-12-18 18 48 05" src="https://github.com/elizabethsiegle/gemini-multimodal-chat/assets/5414949/fb85d70c-ecd6-42d0-a7f7-d9c29813e6fb">

I open a white background input box, but the text color is also white, which needs to be resolved.

**Comment by elizabethsiegle** [comment]
This isn't a code fix, this can be changed in your Replit app settings. 
<img width="494" alt="Replit app settings" src="https://github.com/elizabethsiegle/gemini-multimodal-chat/assets/8932430/62c16278-4cb8-4f11-9cff-1df129e037e3">
